### PR TITLE
Update sysinfo version

### PR DESCRIPTION
**Pull request by GuillaumeGomez**

### CODE REVIEW

**Comment by ClementTsang** [comment]
Seems like there's similar problems as with https://github.com/ClementTsang/bottom/pull/639 with breaking changes.

**Comment by GuillaumeGomez** [comment]
Interesting that I couldn't trigger it locally... I'll give it another try tomorrow if I don't forget...

**Comment by GuillaumeGomez** [comment]
Updated!

**Comment by GuillaumeGomez** [comment]
Let's hope I didn't forget something again... (Please run CI ^^)

**Comment by GuillaumeGomez** [comment]
CI is happy! \o?

**Comment by ClementTsang** [comment]
LGTM. Thanks for doing this!

Also thanks a ton for the sysinfo library in general!

@all-contributors add @GuillaumeGomez for code

**Comment by GuillaumeGomez** [comment]
You're very welcome! Thanks for using it. :)

**Pull request merged**
