### PR TITLE
feature: support default selection of average CPU graph

### PR DESCRIPTION
**Pull request by ClementTsang**
## Description

_A description of the change, what it does, and why it was made. If relevant (such as any change that modifies the UI), **please provide screenshots** of the changes:_

## Issue

_If applicable, what issue does this address?_

Closes: #1350

## Testing

_If relevant, please state how this was tested. All changes **must** be tested to work:_

_If this is a code change, please also indicate which platforms were tested:_

- [ ] _Windows_
- [ ] _macOS_
- [ ] _Linux_

## Checklist

_If relevant, ensure the following have been met:_

- [ ] _Areas your change affects have been linted using rustfmt (`cargo fmt`)_
- [ ] _The change has been tested and doesn't appear to cause any unintended breakage_
- [ ] _Documentation has been added/updated if needed (`README.md`, help menu, doc pages, etc.)_
- [ ] _The pull request passes the provided CI pipeline_
- [ ] _There are no merge conflicts_
- [ ] _If relevant, new tests were added (don't worry too much about coverage)_

### CODE REVIEW

**Comment by ShalokShalom** [comment]
I see yet no handle, is this intended? 
(Command line flag, option)

**Comment by ClementTsang** [comment]
Intended.

**Comment by ShalokShalom** [comment]
Ah shit. I do think this update will not work for my use case then. 
Why do you want to remove command line flags, if you may like to specify..?
That seems rather regressive.

**Comment by ClementTsang** [comment]
I'm not removing any at the moment, but I would prefer to add _new_ functionality behind configs unless it makes sense to add a corresponding command line arg.

My personal understanding of a flag like this is that it's something you generally would want set permanently...

**Comment by ClementTsang** [comment]
That said, if there is interest in having it as a command line argument, I'll take al ook.

**Comment by ShalokShalom** [comment]
> My personal understanding of an option like this is that it's something you generally would want set permanently... hence why I only made it a config file option.

The way I make this permanent, is via a command line option. I have an alias for starters, and not even touched the config file yet. It would be one more config file to maintain and keep up in my head. And I prefer to just have one alias line in my shell config, and thats it. 

Now removing already used command line arguments would also break the user flow (scripts, again aliases in configurations) for a minor improvement, imho.

**Comment by ClementTsang** [comment]
Major versions are declared as breaking, so :shrug: - I'm not the Rust project that plans on supporting every decision I've made in the past. That said, as I mentioned above, I am not removing current command line arguments at the moment. 

The config managing thing also wouldn't be an issue if I finally get time to land #159. That said, both of these topics are beyond the point of this PR.

As for something on-topic, I'll look at adding a command-line arg, I think I'm okay with it if I reorganize a few things first.

**Comment by ShalokShalom** [comment]
Should I create a new issue for it?

**Comment by ClementTsang** [comment]
It's fine, no need since I'll probably just do it tonight.

**Pull request merged**
