### PR TITLE
chore(deps): upgrade ratatui to 0.26 and crossterm to 0.27

### PR DESCRIPTION
**Pull request by joshka**
- chore(deps): upgrade ratatui to 0.26 and crossterm to 0.27
  - Three major breaking changes:
  - `Spans` was renamed to `Line` several versions ago
  - `Frame` no longer requires a `Backend` type parameter
  - `Table::new()` now requires a widths parameter
- fix: clippy lints

## Description

updates ratatui

## Issue

_If applicable, what issue does this address?_

Closes: #

## Testing

_If relevant, please state how this was tested. All changes **must** be tested to work:_

_If this is a code change, please also indicate which platforms were tested:_

- [ ] _Windows_
- [x] _macOS_
- [ ] _Linux_

## Checklist

_If relevant, ensure the following have been met:_

- [x] _Areas your change affects have been linted using rustfmt (`cargo fmt`)_
- [x] _The change has been tested and doesn't appear to cause any unintended breakage_
- [ ] _Documentation has been added/updated if needed (`README.md`, help menu, doc pages, etc.)_
- [ ] _The pull request passes the provided CI pipeline_
- [ ] _There are no merge conflicts_
- [ ] _If relevant, new tests were added (don't worry too much about coverage)_

### CODE REVIEW

**Comment by ClementTsang** [comment]
You might need to rebase your version, seems like a bunch of stuff is outdated on your branch.

I can also just tackle the upgrade, should be pretty small since the bump is just 0.25 -> 0.26.

**Comment by ClementTsang** [comment]
Closing in favour of #1406.

**Comment by joshka** [comment]
> You might need to rebase your version, seems like a bunch of stuff is outdated on your branch. You're 200 commits behind `main` from the looks of it.

Oops - sorry about that. Seems my git pull failed for some reason and I didn't notice :D

**Comment by ClementTsang** [comment]
Might have been due to me changing the head branch from `master` to `main` sometime last year... maybe that tripped git up.

**Comment by joshka** [comment]
> Might have been due to me changing the head branch from `master` to `main` sometime last year... maybe that tripped git up.

Ha - yup that was it indeed

**Pull request closed without merging**
