### PR TITLE
do not crash when run on read-only file system

### PR DESCRIPTION
**Pull request by harrysarson**
## Description

Prior to this change I get an error when running `btm` on a system with a read-only filesystem:

    Error: InvalidIO("Read-only file system (os error 30)") 

This PR adds a special case in the error handling for os errors with code 39 (See https://mariadb.com/kb/en/operating-system-error-codes/ which I used as a reference).

## Type of change

_Remove the irrelevant ones:_

- [x] _Bug fix (non-breaking change which fixes an issue)_

## Test methodology

Tested by running on a linux system I have access to (with read only file system).

- [ ] _Windows_
- [ ] _macOS_
- [x] _Linux_

I do not have access to mac or windows systems with read-only filesystems to test.

## Checklist

_If relevant, ensure the following have been met:_

- [x] _Change has been tested to work, and does not cause new breakage unless intended_
- [x] _Code has been self-reviewed_
- [ ] _Documentation has been added/updated if needed (README, help menu, etc.)_
- [x] _Passes Travis tests (clippy check and `cargo test` check)_
- [x] _Areas your change affects have been linted using rustfmt (`cargo fmt`)_
- [x] _No merge conflicts arise from the change_

## Other information

_Provide any other relevant information to this change:_

### CODE REVIEW

**Comment by ClementTsang** [comment]
General concept LGTM, but you might have to change it a bit to deal with the merge conflict and changes since the original fork.

**Comment by harrysarson** [comment]
Ah sorry I checked put the local release when building locally. Will fix 👍

**Comment by harrysarson** [comment]
Rebased :)

**Comment by harrysarson** [comment]
Thinking about this some more, I am not sure this is the correct approach. If a user explicitly choses the location of the configuration file `btm` should _not_ fail silently if it cannot write the file. It should only ignore the read only filesystem errors when using the default config file location.

**Comment by ClementTsang** [comment]
> Thinking about this some more, I am not sure this is the correct approach. If a user explicitly choses the location of the configuration file btm should not fail silently if it cannot write the file. It should only ignore the read only filesystem errors when using the default config file location.

Hmm... yeah, that makes more sense.  That would work for now IMO.

Ideally I would prefer to just give a dialog warning the user that their config file location is not writable prior to showing any data, though that's a bit more complicated than the original idea.

**Comment by harrysarson** [comment]
Hey! Because I am not convinced this is the right approach and because I am low on time this month and because there is a workaround (telling btm to write the config to `/tmp` or somewhere memory backed filesystem). I am going to close this to avoid a stale PR in your repo.

Thanks for all your time on this!

**Pull request closed without merging**
