### PR TITLE
Fix Clippy warnings

### PR DESCRIPTION
**Pull request by mati865**
## Description

Fixes warnings printed by Clippy when building the code.

## Issue

_If applicable, what issue does this address?_

Closes: #

## Testing

_If relevant, please state how this was tested. All changes **must** be tested to work:_

_Please also indicate which platforms were tested. All platforms directly affected by the change **must** be tested:_

- [ ] _Windows_
- [ ] _macOS_
- [x] _Linux_

## Checklist

_If relevant, ensure the following have been met:_

- [x] _Areas your change affects have been linted using rustfmt (`cargo fmt`)_
- [x] _The change has been tested and doesn't appear to cause any unintended breakage_
- [ ] _Documentation has been added/updated if needed (`README.md`, help menu, etc.)_
- [ ] _The pull request passes the provided CI pipeline_
- [ ] _There are no merge conflicts_

### CODE REVIEW

**Comment by ClementTsang** [comment]
Thanks.  Out of curiosity, are you using nightly/beta clippy warnings?

**Comment by mati865** [comment]
> Out of curiosity, are you using nightly/beta clippy warnings?

Nightly but would not recommend that for CI.

**Comment by ClementTsang** [comment]
Yeah, no plans on moving that.  Was just curious since clippy stable has been showing up clean on the pipeline, but I knew that nightly/beta sometimes has newer checks.

**Comment by ClementTsang** [comment]
LGTM.  Thanks again!

@all-contributors add @mati865 for code

**Pull request merged**
