### PR TITLE
feat: add option to move avg CPU to another row

### PR DESCRIPTION
**Pull request by zebp**
## Description

Adds an `average_cpu_row` option to move the average CPU usage to its own row when using basic mode.

image

## Issue

I didn't make an issue for this, I did this for myself but thought I might as well try to upstream.

## Testing

Tested by turning on and off the new layout via cli flag and config file entry and ensuring the layout was rendered accordingly.

- [x] _Windows_
- [x] _macOS_
- [x] _Linux_

## Checklist

- [x] _Areas your change affects have been linted using rustfmt (`cargo fmt`)_
- [x] _The change has been tested and doesn't appear to cause any unintended breakage_
- [x] _Documentation has been added/updated if needed (`README.md`, help menu, doc pages, etc.)_
- [ ] _The pull request passes the provided CI pipeline_
- [x] _There are no merge conflicts_
- [x] _If relevant, new tests were added (don't worry too much about coverage)_

### CODE REVIEW

**Comment by zebp** [comment]
CI passes for the most part, the only failures are codecov ratelimiting

**Comment by ClementTsang** [comment]
Sorry for the delay - I'll look at it by the weekend.

> the only failures are codecov ratelimiting

Yep, that's fine.

**Comment by zebp** [comment]
Rebased to resolve merge conflicts

**Review by ClementTsang — CHANGES_REQUESTED** [review]
Sorry that took so long - overall looks fine, left a few comments, and needs to be rebased.

**Comment by zebp** [comment]
Rebased and addressed feedback

**Review by ClementTsang — APPROVED** [review]
LGTM. Thanks for the PR!

**Pull request merged**
