### PR TITLE
create config if doesnt exist

### PR DESCRIPTION
**Pull request by shilangyu**
## Description

Creates a config file if it doesnt exist:
- in the specified default path [here](https://github.com/ClementTsang/bottom/blob/master/docs/config.md#default-config-locations)
- in the path passed by the `-C` flag

## Issue

Closes: #37

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Test methodology

None yet, i will be happy to write tests for it if the current implementation is accepted

## Checklist

- [ ] Change has been tested to work
- [x] Areas your change affects has been linted using rustfmt
- [x] Code has been self-reviewed
- [x] Code has been tested and no new breakage is introduced
- [x] Documentation has been added/updated if needed

## Other information

This is my first ever contribution in Rust! Please let me know if something is wrong, I will correct it ASAP. If the implementation is fine I will add a test for it and change the documentation to reflect the change :)

### CODE REVIEW

**Comment by shilangyu** [comment]
The conflict arose from running `cargo +nightly fmt`

**Comment by ClementTsang** [comment]
@shilangyu Looks good to me.

Before I accept, can you just make sure you test this?  Worked fine on my Linux system, but if possible, testing on other platforms would be great.

**Comment by ClementTsang** [comment]
btw if you can't test on other platforms but your main one it's fine, just want to know how you're going about testing it and I can replicate on other machines.

**Comment by shilangyu** [comment]
Sorry for not replying yesterday. I will manually test on a Windows machine (tested on my linux machine already), then I'll try to write automated tests for it. 
- check if config is created in default path
- check if config is created in `-C` path
- check if config isn't overwritten if already exists
Thanks for letting me do this, helps a ton in getting into the rust open source world

**Comment by shilangyu** [comment]
Writing tests that act on the binary directly ended up being pretty hard because the TUI starts and doesn't exit (which explains why current tests are for _failing_ runs).

I tested manually on my machine (Fedora). Couldn't test on windows nor MacOs.

**Comment by ClementTsang** [comment]
> Automated tests

Yeah, that's fine.  Mostly was expecting just manual testing to ensure that the feature is good without breakage.

> Couldn't test on OSX or Windows

That's fine, I'll probably do that on my own and if it's good, I'll accept the PR.

**Comment by ClementTsang** [comment]
@all-contributors add @shilangyu for code

**Pull request merged**
